package:
  name: go-tool
  version: 1.2.1

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1 
  noarch: python
  # Clone modified version of go-tool which includes support for Powershell
  script: hg clone http://hg.skepticats.com/go-posh && cd go-posh && python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - mercurial

about:
  licence: MIT
  url: https://github.com/trentm/go-tool
